export const CREATE_PROJECT = 'CREATE_PROJECT';

export const LIST_ALL_PRODUCT = 'LIST_ALL_PRODUCT';
export const LIST_PRODUCT_BY_BRAND = 'LIST_PRODUCT_BY_BRAND';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const SORT_PRODUCT = 'SORT_PRODUCT';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';

export const LIST_ALL_USER = 'LIST_ALL_USER';
export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export const EDIT_ACCOUNT = 'EDIT_ACCOUNT';
export const LOGOUT = 'LOGOUT';

export const LIST_COMMENT = 'LIST_COMMENT';
export const ADD_COMMENT = 'ADD_COMMENT';

export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_PRODUCT_CART = 'DELETE_PRODUCT_CART';
export const INCREASE_QUANTITY_PRODUCT_CART = 'INCREASE_QUANTITY_PRODUCT_CART';
export const REDUCE_QUANTITY_PRODUCT_CART = 'REDUCE_QUANTITY_PRODUCT_CART';

export const CREATE_ORDER = 'CREATE_ORDER';

export const CREATE_ACCOUNT_ADMIN = 'CREATE_ACCOUNT_ADMIN';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_PRODUCT_NEW = 'SET_PRODUCT_NEW';
export const SET_USER = 'SET_USER';
export const SET_ORDERS = 'SET_ORDERS';
export const SET_CARTS = 'SET_CARTS';
export const SET_COMMENTS = 'SET_COMMENTS';
